baseURL = "krevkodes.github.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "KrevKodes"
theme = "papercss-hugo-theme"
googleAnalytics = "UA-123456789-1"
paginate = 5

[privacy.disqus]
disable = true

[taxonomies]
tag = "tags"

[permalinks]
post = "/:filename/"

[imaging]
quality = 99

[params]
homeMetaContent = "A Hugo theme made with PaperCSS, the less formal CSS framework."
dateFormat = "Jan 2, 2006"
navTitleLink = "/"

[[menu.nav]]
name = "Social"
url = "https://www.youtube.com/channel/UCEjF0_xMLreULwUPmNsJUqg"
weight = 1


[[menu.nav]]
name = "About"
url = "/about"
weight = 2

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

  [markup.highlight]
  codeFences = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

  [markup.tableOfContents]
  endLevel = 6
  startLevel = 2

